### ISSUE TITLE
FR: Allow keyword for the color of `rangeslider`

### ISSUE THREAD

**Issue by Datseris** [piever/InteractBase.jl#114]
The `rangeslider` widget is super-pretty!

You know what would be even prettier? Having it in many colors! It would be awesome if a keyword argument could let you specify a color for the slider! This teal-like color is really good but a choice would be even better!

**Comment by piever** [comment]
Ideally this should work like all other widgets using Bulma modifiers (see [here](https://bulma.io/documentation/modifiers/color-helpers/) and [here](https://wikiki.github.io/form/slider/) for the slider case). `rangeslider` is a bit of an exception as is the only widget that doesn't come from Bulma or Bulma extensions (as sliders with several handles do not exist in pure HTML5 so this needs a custom javascript library). The default color is also off because of this: all other widgets default to turquoise rather than teal.

I'll see if I can get it to work consistenty also for `rangeslider` and then will start to document this side of things a bit more (widget styling is possible but WIP and I prefer to only document things when I am confident they work).

**Comment by Datseris** [comment]
Awesome! Having colors would be cool! Kind of dissapointed that Bulma does not have purple color (very weird) but I'll live with it...

> (widget styling is possible but WIP and I prefer to only document things when I am confident they work).

+100 this is how you make a user-friendly documentation

**Comment by piever** [comment]
Sneak preview:

![Screenshot from 2019-04-02 20-31-20](https://user-images.githubusercontent.com/6333339/55430578-6598c480-5586-11e9-95e5-0cfcb2908179.png)

with a custom theme:

![Screenshot from 2019-04-02 20-31-32](https://user-images.githubusercontent.com/6333339/55430591-6c273c00-5586-11e9-8c2d-b554e2d0c5c3.png)

Requires InteractBase 0.10 and https://github.com/JuliaGizmos/Interact.jl/pull/302 (should merge and release soonish).

**Comment by Datseris** [comment]
Nice! it is not possible to specify color through (R, G, B)? If not, where is the "string to color" table listed?

**Comment by Datseris** [comment]
ops so sorry, forgot you have already linked this in your previous comment. (was some time ago!)

**Comment by piever** [comment]
No problem! I'm no web-designer (not even close) but from what I understand it is not encouraged to use RGB values directly to style your web page. Bulma by default provides a few colors and shades of grey listed [here](https://bulma.io/documentation/modifiers/color-helpers/). If you dislike that color-scheme, you can create your own, you just need a `_variables.scss` file with your own values.

```julia
using InteractBulma: compile_theme, examplefolder
variables_file = joinpath(examplefolder, "flatly", "_variables.scss") # here you would use your own style
mytheme = compile_theme(variables = variables_file)
settheme!(mytheme)
```

The customized `_variables.scss` is actually quite easy to make. For example, [this](https://github.com/piever/InteractBulma.jl/blob/master/examples/base16/_variables.scss) is one I just added taking colors from the Base16 atom theme, which gives as output:

![Screenshot from 2019-04-02 23-46-46](https://user-images.githubusercontent.com/6333339/55441195-de594a00-55a1-11e9-9f1c-5b9763e41e4f.png)

I imagine also plotting palettes could probably be used to make themes though I haven't tried yet. If you have a specific combination of colors you like to use, feel free to PR it to InteractBulma, I'd be happy to have a bunch of themes there.

**Comment by piever** [comment]
Closing as the new Interact version has just been released.
