### ISSUE TITLE
Cannot use backspace or arrow keys in textbox.

### ISSUE THREAD

**Issue by korsbo** [piever/InteractBase.jl#12]
When trying out textbox (using the Bulma backend) in Juno, I found that some normal keyboard input is ignored. I cannot use backspace, nor can I use the arrow keys to navigate in the text. I can however drag and drop parts of the text, indicating that it is possible to edit it. 

```julia
using WebIO
using InteractBulma

textbox()
```

This is not important to me, I just thought that I'd raise the issue.

**Comment by piever** [comment]
Thanks for reporting. I had raised the issue [here](https://github.com/JunoLab/Juno.jl/issues/138#issuecomment-390399319) (the issue has instructions on how to fix locally, by editing some configuration atom file).

It's already fixed in [atom-julia-client master](https://github.com/JunoLab/atom-julia-client/commit/8086a94c3c3f84c58b5b25f2f94763cd6fefc4ae).

**Comment by korsbo** [comment]
Cool, cheers!
